spring.application.name=Homework-Ignitis

spring.datasource.url=jdbc:h2:mem:chatdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

spring.web.error.include-message=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false

springdoc.api-docs.version=OPENAPI_3_0

app.security.jwt.secret=${JWT_SECRET:super-completely-secret-secret-no-one-will-ever-guess}
app.security.jwt.expires-in=PT1H

app.security.bootstrap-admin.username=${BOOTSTRAP_ADMIN_USERNAME:admin}
app.security.bootstrap-admin.password=${BOOTSTRAP_ADMIN_PASSWORD:admin-password}
